### ISSUE TITLE
Intermittent Communication Failures Running on macOS Laptop

### ISSUE THREAD

**Issue by tshead2** [cicada-mpc/cicada-mpc#4]
Feature: Shamir Protocol # features/shamir.feature:1

  Scenario: Inter-session Repetition                          # features/shamir.feature:3
    Given 5 players                                           # features/steps/communication_steps.py:26 0.000s
    And a minimum of 3 shares to recover a secret             # features/steps/shamir_steps.py:26 0.000s
    When shamir secret sharing the same value for 10 sessions # features/steps/shamir_steps.py:31 1.024s
    Then the shares should never be repeated                  # features/steps/additive_steps.py:63 0.019s

  Scenario: Intra-session Repetition                                  # features/shamir.feature:10
    Given 5 players                                                   # features/steps/communication_steps.py:26 0.000s
    And a minimum of 3 shares to recover a secret                     # features/steps/shamir_steps.py:26 0.000s
    When shamir secret sharing the same value 10 times in one session # features/steps/shamir_steps.py:47 5.122s
      Traceback (most recent call last):
        File "/Users/tshead/miniconda3/lib/python3.7/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/Users/tshead/miniconda3/lib/python3.7/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/shamir_steps.py", line 57, in step_impl
          context.shares = numpy.column_stack(operation(count))
        File "<__array_function__ internals>", line 6, in column_stack
        File "/Users/tshead/miniconda3/lib/python3.7/site-packages/numpy/lib/shape_base.py", line 656, in column_stack
          return _nx.concatenate(arrays, 1)
        File "<__array_function__ internals>", line 6, in concatenate
      ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 3 dimension(s) and the array at index 3 has 2 dimension(s)
      
      Captured logging:
      INFO:cicada.communicator.nng:Player 0 returned: [array([[1, -151096090296386491763386488625072816819]], dtype=object), array([[1, -15861419888184548005501680606067226947]], dtype=object), array([[1, 30281067081391646379380932929288710910]], dtype=object), array([[1, -95601869735652756775825147718581419621]], dtype=object), array([[1, 115396334310742177656216189838573493764]], dtype=object), array([[1, 8828274699586319622412256358238029919]], dtype=object), array([[1, 54921396036719033157954439822981355356]], dtype=object), array([[1, -41132530698322089298430684208296745240]], dtype=object), array([[1, -24290717048849943638568629446018495753]], dtype=object), array([[1, -17746897303067774245057383412088692549]], dtype=object)]
      INFO:cicada.communicator.nng:Player 1 returned: [array([[2, -26186581947012373869921299280541971265]], dtype=object), array([[2, -50544324711149393508304565884335013161]], dtype=object), array([[2, -6519914837210945858096664895621529482]], dtype=object), array([[2, -31805981620060960450011916766383268467]], dtype=object), array([[2, 58812093496967849476059821083585562137]], dtype=object), array([[2, 66533279654814973678675517208890749553]], dtype=object), array([[2, -16733642799313185055116770139057379253]], dtype=object), array([[2, -57932601329307344990103721800102606095]], dtype=object), array([[2, 35380048967882064315991793843489715207]], dtype=object), array([[2, 52617907298320784067795069465276178525]], dtype=object)]
      INFO:cicada.communicator.nng:Player 2 returned: [array([[3, -135695025333285341514666343114059780514]], dtype=object), array([[3, 66092468991574695223278647881080747090]], dtype=object), array([[3, 59738237704661455019254510241153384556]], dtype=object), array([[3, 21246480886306157245752389140710347740]], dtype=object), array([[3, 388461019146247191218197450920310851]], dtype=object), array([[3, 2973831405216730437102478836074053180]], dtype=object), array([[3, 125317250412841808824160977545652007632]], dtype=object), array([[3, -50400211892955767075019112775417582560]], dtype=object), array([[3, 8871114589726792131993966152640527158]], dtype=object), array([[3, 40953230343696443206870054916210507500]], dtype=object)]
      ERROR:cicada.communicator.nng:Player 3 failed: Timeout("Tag 'scatterv' from sender 0 timed-out after 5s")
      INFO:cicada.communicator.nng:Player 4 returned: [array([[5, -37118666549957143028663308019936729059]], dtype=object), array([[5, 72760418132212748462854157679426484079]], dtype=object), array([[5, -8991604211576459076618731747893641259]], dtype=object), array([[5, -75020054389102874984553077896300130414]], dtype=object), array([[5, 48164204531830452039166489268441955029]], dtype=object), array([[5, 22485125672947247255509415567684729594]], dtype=object), array([[5, 29689732218898042469639523560010511522]], dtype=object), array([[5, 37661947181757889575423045123425117680]], dtype=object), array([[5, 37596511569692870811698165261638165487]], dtype=object), array([[5, -58323384773121704304625072745328355120]], dtype=object)]
      ERROR:cicada.communicator.nng:********************************************************************************
      ERROR:cicada.communicator.nng:Player 3 traceback:
      ERROR:cicada.communicator.nng:Traceback (most recent call last):
        File "/Users/tshead/src/cicada-mpc/cicada/communicator/nng.py", line 356, in _receive
          return self._receive_queues[tag][sender].get(block=block, timeout=self._timeout)
        File "/Users/tshead/miniconda3/lib/python3.7/queue.py", line 178, in get
          raise Empty
      _queue.Empty
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/Users/tshead/src/cicada-mpc/cicada/communicator/nng.py", line 703, in launch
          result = func(communicator, *args, **kwargs)
        File "features/steps/shamir_steps.py", line 54, in operation
          shares = [protocol.share(src=0, k=context.k, secret=numpy.array(5))._storage for i in range(count)]
        File "features/steps/shamir_steps.py", line 54, in <listcomp>
          shares = [protocol.share(src=0, k=context.k, secret=numpy.array(5))._storage for i in range(count)]
        File "/Users/tshead/src/cicada-mpc/cicada/shamir.py", line 210, in share
          shares = self.communicator.scatterv(src=src, values=values, dst=dst)
        File "/Users/tshead/src/cicada-mpc/cicada/communicator/nng.py", line 811, in scatterv
          message = self._receive(tag="scatterv", sender=src, block=True)
        File "/Users/tshead/src/cicada-mpc/cicada/communicator/nng.py", line 359, in _receive
          raise Timeout(f"Tag {tag!r} from sender {sender} timed-out after {self._timeout}s")
      cicada.communicator.nng.Timeout: Tag 'scatterv' from sender 0 timed-out after 5s

    Then the shares should never be repeated                          # None

**Comment by tshead2** [comment]
So I don't forget: this happened four times in fifteen runs.

**Comment by tshead2** [comment]
Fixed with SocketCommunicator.
